name: Build and Push Cog Model to Replicate

on:
  push:
    branches: [ main ] # Trigger on pushes to the main branch
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  build_and_push:
    runs-on: ubuntu-latest # Use a standard Linux runner
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # NOTE: Setting up Docker/Buildx is often needed for advanced builds,
      # but Cog typically handles this internally if docker is available.
      # If issues arise, consider adding Docker setup steps like:
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Install Cog
        run: sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/latest/download/cog_`uname -s`_`uname -m` && sudo chmod +x /usr/local/bin/cog

      - name: Explicitly Compile CUDA Kernel using Docker
        # Use a Docker container with the correct CUDA toolkit version
        # Mount the workspace to access source code and output the PTX file
        run: |
          echo "Attempting to compile CUDA kernel using Docker..."
          docker run --rm \
            -v ${{ github.workspace }}/core/cuda:/workdir \
            nvidia/cuda:11.8.0-devel-ubuntu22.04 \
            sh -c "nvcc --ptx -arch=sm_70 -O3 -I./cuda-ecc-ed25519 --std=c++11 vanity_generator.cu -o kernel.ptx > nvcc_stdout.log 2> nvcc_stderr.log" || true

          echo "--- NVCC STDOUT (from container) ---"
          # Need to check if the file exists inside the container or output dir
          # Since we mounted, the logs *should* be in the host dir now
          cat ${{ github.workspace }}/core/cuda/nvcc_stdout.log || echo "stdout log not found"
          echo "--- NVCC STDERR (from container) ---"
          cat ${{ github.workspace }}/core/cuda/nvcc_stderr.log || echo "stderr log not found"

          # Check if compilation failed (stderr log has content)
          if [ -s ${{ github.workspace }}/core/cuda/nvcc_stderr.log ]; then
            echo "NVCC compilation failed. See errors above."
            exit 1 # Fail the workflow step
          fi
          echo "NVCC compilation successful (kernel.ptx created in ./core/cuda/)."

      - name: Build Cog model image (uses pre-compiled kernel.ptx)
        # This command now expects kernel.ptx to exist from the previous step
        run: cog build -t solvanitycl-temp-build # Use a temporary tag

      - name: Log in to Replicate
        # Use the REPLICATE_API_TOKEN secret stored in GitHub repo settings
        if: github.event_name == 'push' # Only login/push on actual push events
        run: echo "${{ secrets.REPLICATE_API_TOKEN }}" | cog login

      - name: Push image to Replicate
        # Cog push reads the destination from the 'image:' field in cog.yaml
        if: github.event_name == 'push' # Only login/push on actual push events
        run: cog push
